### ISSUE TITLE
Composer replace no longer working for Magento 2.4.5

### ISSUE THREAD

**Issue by linshin** [yireo/magento2-replace-all#28]
After upgrading Magento to 2.4.5 I'm getting the following error when I'm trying to replace vendor packages. I'm using the latest 2.2.x Composer version.

**Your lock file does not contain a compatible set of packages. Please run composer update.**

 ```
 Problem 1
    - magento/project-community-edition is present at version 2.4.5 and cannot be modified by Composer
    - Only one of these can be installed: magento/module-remote-storage[100.4.3], magento/project-community-edition[2.4.5]. magento/project-community-edition replaces magento/module-remote-storage and thus cannot coexist with it.
    - magento/module-remote-storage is locked to version 100.4.3 and an update of this package was not requested.
```

I'm not sure if this is a problem of composer in general or not.

**Comment by jissereitsma** [comment]
Did you see already the troubleshooting hints here - https://github.com/yireo/magento2-replace-tools ? Often a simple `composer update` does not work because the replacements require a complete new build of the lock file. Throwing away `vendor/` and the lock file are maybe not to be recommended when working with composer normally, but it is recommended when working with replacements like these.

**Comment by OLTC-fperrin** [comment]
magento/module-remote-storage is required by magento/module-aws-s3
that module is not supposed to be replaced really so you should be fine if you remove `"magento/module-remote-storage": "*"` from your composer replace

**Comment by jissereitsma** [comment]
A new release has been made, removing `magento/module-aws-s3` as well. The intention of this meta-package is to remove as much as possible. As of yet, no issues are found.
